export const categories = [
  ".NET",
  "AI",
  "Blockchain",
  "Blog",
  "Business",
  "Data Engineering",
  "DBI",
  "Golang",
  "Java",
  "JavaScript",
  "Mobile App Development",
  "MVP",
  "Personal",
  "Programming & Development",
  "Python",
  "React",
  "Software Development",
  "SQL Server",
  "Staff Augmentation",
  "Technology",
  "Web",
];
